import type { ManifestArtifact, CatalogArtifact } from '../../utils/load/types';

export const testManifest: ManifestArtifact = {
	metadata: {
		dbt_schema_version: 'https://schemas.getdbt.com/dbt/manifest/v12.json',
	},
	nodes: {
		model_node: {
			database: 'test_db',
			schema: 'stg',
			name: 'model_node',
			resource_type: 'model',
			package_name: 'test_pkg',
			path: 'models/stg/model_node.sql',
			original_file_path: 'models/stg/model_node.sql',
			unique_id: 'model.test_pkg.model_node',
			fqn: ['test_pkg', 'model_node', 'v1'],
			alias: 'model_node_alias',
			checksum: {
				name: 'sha256',
				checksum: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
			},
			config: { materialized: 'table' },
			columns: {
				id: { name: 'id', info: 1 },
				name: { name: 'name', info: 2 },
				mixedCase: { name: 'mixedCase', info: 3 },
			},
			version: 1,
		},
		snapshot_node: {
			database: 'test_db',
			schema: 'snap',
			name: 'snapshot_node',
			resource_type: 'snapshot',
			package_name: 'test_pkg',
			path: 'snapshots/snapshot_node.sql',
			original_file_path: 'snapshots/snapshot_node.sql',
			unique_id: 'snapshot.test_pkg.snapshot_node',
			fqn: ['test_pkg', 'snapshot_node'],
			alias: 'snapshot_node_alias',
			checksum: {
				name: 'sha256',
				checksum: 'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
			},
			config: { materialized: 'snapshot' },
			columns: {},
		},
		seed_node: {
			database: 'test_db',
			schema: 'raw',
			name: 'seed_node',
			resource_type: 'seed',
			package_name: 'test_pkg',
			path: 'seeds/seed_node.csv',
			original_file_path: 'seeds/seed_node.csv',
			unique_id: 'seed.test_pkg.seed_node',
			fqn: ['test_pkg', 'seed_node'],
			alias: 'seed_node_alias',
			checksum: {
				name: 'sha256',
				checksum: 'cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc',
			},
			columns: {
				seed_col: { name: 'seed_col', info: 1 },
			},
		},
		analysis_node: {
			database: 'test_db',
			schema: 'analysis',
			name: 'analysis_node',
			resource_type: 'analysis',
			package_name: 'test_pkg',
			path: 'analysis/analysis_node.sql',
			original_file_path: 'analysis/analysis_node.sql',
			unique_id: 'analysis.test_pkg.analysis_node',
			fqn: ['test_pkg', 'analysis_node'],
			alias: 'analysis_node_alias',
			checksum: {
				name: 'sha256',
				checksum: 'dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd',
			},
			columns: {},
		},
		protected_model: {
			database: 'test_db',
			schema: 'stg',
			name: 'protected_model',
			resource_type: 'model',
			package_name: 'test_pkg',
			path: 'models/stg/protected_model.sql',
			original_file_path: 'models/stg/protected_model.sql',
			unique_id: 'model.test_pkg.protected_model',
			fqn: ['test_pkg', 'protected_model'],
			alias: 'protected_model_alias',
			checksum: {
				name: 'sha256',
				checksum: 'eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
			},
			access: 'protected',
			columns: {},
		},
		private_model: {
			database: 'test_db',
			schema: 'stg',
			name: 'private_model',
			resource_type: 'model',
			package_name: 'test_pkg',
			path: 'models/stg/private_model.sql',
			original_file_path: 'models/stg/private_model.sql',
			unique_id: 'model.test_pkg.private_model',
			fqn: ['test_pkg', 'private_model'],
			alias: 'private_model_alias',
			checksum: {
				name: 'sha256',
				checksum: 'ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff',
			},
			access: 'private',
			columns: {},
		},
		hidden_node: {
			database: 'test_db',
			schema: 'hidden',
			name: 'hidden_node',
			resource_type: 'model',
			package_name: 'test_pkg',
			path: 'models/hidden/hidden_node.sql',
			original_file_path: 'models/hidden/hidden_node.sql',
			unique_id: 'model.test_pkg.hidden_node',
			fqn: ['test_pkg', 'hidden_node'],
			alias: 'hidden_node_alias',
			checksum: {
				name: 'sha256',
				checksum: 'abababababababababababababababababababababababababababababababab',
			},
			docs: { show: false },
			columns: {},
		},
	},
	sources: {
		source1: {
			database: 'db1',
			schema: 'public',
			name: 'source1',
			resource_type: 'source',
			package_name: 'test_pkg',
			path: 'models/sources.yml',
			original_file_path: 'models/sources.yml',
			unique_id: 'source.test_pkg.s1.source1',
			fqn: ['test_pkg', 's1', 'source1'],
			source_name: 's1',
			source_description: 'Primary public source',
			loader: 'snowflake',
			identifier: 'source1',
			columns: {},
		},
		source2: {
			database: null, // edge case: unset database
			schema: 'raw',
			name: 'source2',
			resource_type: 'source',
			package_name: 'test_pkg',
			path: 'models/raw/sources.yml',
			original_file_path: 'models/raw/sources.yml',
			unique_id: 'source.test_pkg.s2.source2',
			fqn: ['test_pkg', 's2', 'source2'],
			source_name: 's2',
			source_description: '',
			loader: 'bigquery',
			identifier: 'src_02',
			columns: {},
		},
	},
	macros: {
		macro1: {
			name: 'macro1',
			resource_type: 'macro',
			package_name: 'test_pkg',
			original_file_path: 'macros/macro1.sql',
			unique_id: 'macro.test_pkg.macro1',
			path: 'macros/macro1.sql',
			macro_sql: 'select 1;',
		},
	},
	exposures: {
		exposure1: {
			name: 'exposure1',
			resource_type: 'exposure',
			package_name: 'test_pkg',
			path: 'models/exposures.yml',
			original_file_path: 'models/exposures.yml',
			unique_id: 'exposure.test_pkg.exposure1',
			fqn: ['test_pkg', 'exposure1'],
			type: 'dashboard',
			owner: {
				name: 'Data Team',
				email: 'data@test.com',
			},
		},
	},
	metrics: {
		metric1: {
			name: 'metric1',
			resource_type: 'metric',
			package_name: 'test_pkg',
			path: 'models/metrics.yml',
			original_file_path: 'models/metrics.yml',
			unique_id: 'metric.test_pkg.metric1',
			fqn: ['test_pkg', 'metric1'],
			description: 'Total count of events',
			label: 'Metric 1',
			type: 'simple',
			type_params: {
				measure: { name: 'event_count' },
			},
		},
	},
	semantic_models: {
		sm1: {
			name: 'sm1',
			resource_type: 'semantic_model',
			package_name: 'test_pkg',
			path: 'models/semantic_models.yml',
			original_file_path: 'models/semantic_models.yml',
			unique_id: 'semantic_model.test_pkg.sm1',
			fqn: ['test_pkg', 'sm1'],
			model: 'model.test_pkg.model_node',
			node_relation: null, // edge case: unresolved relation
		},
	},
	saved_queries: {
		sq1: {
			name: 'sq1',
			resource_type: 'saved_query',
			package_name: 'test_pkg',
			path: 'models/saved_queries.yml',
			original_file_path: 'models/saved_queries.yml',
			unique_id: 'saved_query.test_pkg.sq1',
			fqn: ['test_pkg', 'sq1'],
			query_params: {
				metrics: ['metric1'],
				group_by: ['day'],
				where: null,
			},
			exports: [
				{
					name: 'daily_export',
					config: { export_as: 'table' },
				},
			],
		},
	},
	unit_tests: {
		unit_test_1: {
			name: 'unit_test_1',
			resource_type: 'unit_test',
			package_name: 'test_pkg',
			path: 'tests/unit/model_node.yml',
			original_file_path: 'tests/unit/model_node.yml',
			unique_id: 'unit_test.test_pkg.unit_test_1',
			fqn: ['test_pkg', 'unit_test_1'],
			model: 'model.test_pkg.model_node',
			given: [
				{
					input: 'seed.test_pkg.seed_node',
					rows: [{ seed_col: 1 }],
				},
			],
			expect: {
				rows: [{ id: 1, name: 'test' }],
			},
		},
	},
	groups: {},
	selectors: {},
	disabled: {},
	parent_map: {},
	child_map: {},
	group_map: {},
	docs: {},
};

export const testCatalog: CatalogArtifact = {
	metadata: {
		dbt_schema_version: 'https://schemas.getdbt.com/dbt/catalog/v1.json',
	},
	sources: {
		source1: {
			metadata: { type: 'BASE TABLE', schema: 'public', name: 'source1' },
			columns: { field_1: { type: 'TEXT', index: 1, name: 'field_1' } },
			stats: {},
			unique_id: 'source.s1.source1',
		},
		source2: {
			metadata: { type: 'BASE TABLE', schema: 'raw', name: 'source2' },
			columns: { field_a: { type: 'TEXT', index: 1, name: 'field_a' } },
			stats: {},
			unique_id: 'source.s2.source2',
		},
	},
	nodes: {
		model_node: {
			metadata: { type: 'BASE TABLE', schema: 'stg', name: 'model_node' },
			columns: {
				ID: { type: 'TEXT', index: 1, name: 'ID' },
				name: { type: 'TEXT', index: 2, name: 'name' },
				mixedCase: { type: 'TEXT', index: 3, name: 'mixedCase' },
			},
			stats: {},
		},
		snapshot_node: {
			metadata: { type: 'BASE TABLE', schema: 'snap', name: 'snapshot_node' },
			columns: {},
			stats: {},
		},
		seed_node: {
			metadata: { type: 'BASE TABLE', schema: 'raw', name: 'seed_node' },
			columns: { seed_col: { type: 'TEXT', index: 1, name: 'seed_col' } },
			stats: {},
		},
	},
};
